### ISSUE TITLE
Incorrect message being printed in BSMT_GenerateManifest target

### ISSUE THREAD

**Issue by ErisApps** [Zingabopp/BeatSaberModdingTools.Tasks#8]
Just noticed that the following message might have been a copy-pasta error. Was planning on PR'ing a fix, but I wasn't exactly sure what message it was supposed to be, hence this :octocat: issue.
https://github.com/Zingabopp/BeatSaberModdingTools.Tasks/blob/180eda35363544cccc1cd739fb15b1bea9c25cdb/BeatSaberModdingTools.Tasks/BuildTypes/BSMT.BSIPA.targets#L41

**Comment by Zingabopp** [comment]
Thanks, it's for GenerateManifest. The validation will fail if you don't list BSIPA as a dependency unless RequiresBsipa is set to false. Fixed.
